### ISSUE TITLE
Investigate Jetpack compatibility

### ISSUE THREAD

**Issue by joelhawksley** [joelhawksley/SoloFolio#273]

**Comment by christineballisty** [comment]
Just curious about the conflicts with Jetpack? I currently use this plugin and am thinking of switching my theme to SoloFolio. I would like to continue using Jetpack if possible.

**Comment by joelhawksley** [comment]
@christineballisty It's due to the way Jetpack conflicts with the gallery plugin. I'm no longer completing tickets on this project at this time.

**Comment by christineballisty** [comment]
Ok thanks
